# Generated by Django 3.0 on 2019-12-28 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_university_website'),
    ]

    operations = [
        migrations.DeleteModel(
            name='McqChoices',
        ),
    ]
